
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/hospital
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  s3:
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
    bucketName: ${BUCKET_NAME}